name: 'Setup Environment'
description: 'Setup System libraries and tools for CI actions'

runs:
  using: "composite"
  steps:
    - name: Restore Aqua CLI cache
      uses: actions/cache@v4
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
        restore-keys: |
          v1-aqua-installer-${{runner.os}}-${{runner.arch}}-

    - name: Install CLI via aqua installer
      uses: aquaproj/aqua-installer@v2.3.0
      with:
        aqua_version: v2.23.1
        aqua_opts: "" # Unset `-l` option
