on:
  workflow_dispatch:
    inputs:
      gh_env:
        description: 'Environment name'
        required: true
        type: choice
        options:
          - 'staging'
          - 'production'

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-sample.yml
    with:
      gh_env: ${{ github.event.inputs.gh_env}}
    
