on:
  workflow_dispatch:
    inputs:
      gh_env:
        description: 'Environment name'
        required: true
        type: choice
        options:
          - 'staging'
          - 'production'
  workflow_call:
    inputs:
      gh_env:
        description: 'Environment name'
        required: true
        type: string


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: ${{ inputs.gh_env }}

    steps:
    - uses: actions/checkout@v4
